---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: syncrs.syncrd.atteg.com
spec:
  group: syncrd.atteg.com
  names:
    kind: Syncr
    plural: syncrs
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: Syncr is the Schema for the syncrs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SyncrSpec defines the desired state of Syncr
            properties:
              apiGroup:
                description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "make" to regenerate code after modifying this file'
                type: string
              apiResource:
                type: string
              apiVersion:
                type: string
              matchLabels:
                additionalProperties:
                  type: string
                type: object
              name:
                type: string
              namespace:
                type: string
            required:
            - apiGroup
            - apiResource
            - apiVersion
            - matchLabels
            - name
            - namespace
            type: object
          status:
            description: SyncrStatus defines the observed state of Syncr
            type: object
        type: object
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
