---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: syncrd-leader-election-role
  namespace: "{{.Release.Namespace}}"
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: syncrd-manager-role
rules:
- apiGroups:
  - syncrd.atteg.com
  resources:
  - syncrs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - syncrd.atteg.com
  resources:
  - syncrs/status
  verbs:
  - get
  - patch
  - update
- apiGroups: [""]
  resources: ["secrets", "namespaces"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: syncrd-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: syncrd-leader-election-rolebinding
  namespace: "{{.Release.Namespace}}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: syncrd-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: "{{.Release.Namespace}}"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: syncrd-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: syncrd-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: "{{.Release.Namespace}}"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: syncrd-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: syncrd-proxy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: "{{.Release.Namespace}}"
